<a href="https://colab.research.google.com/github/ZahraMansouri-ML/ZahraMansouri-ML/blob/main/into_to_paytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
#paytorch is a library for doing NN
#PyTorch is a machine learning library based on the Torch library,
# used for applications such as computer vision and natural language processing, originally developed by Meta AI and now part of the Linux Foundation umbrella.

First of all, let us install PyTorch and sklearn, two non-standard packages written for Python that we will use in this class.
This is achieved by using "!" magic in Google Colab, which indicates this is not a Python sentence and will behave like a shell command line. Try it and you will expect an automatic download and installation done by pip (-q means silent execution).

In [1]:
!pip install -q torch torchvision

In [1]:
import numpy as np

import torch
import torch.nn as nn
import torch.nn.functional as fn
import torchvision

import sklearn
import matplotlib.pyplot as plt

from PIL import Image

In [3]:
#a tensor with ten number
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#differences between shape and view
https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch

In [13]:
#reshape and view are very similar
#reshape
#we have 10 vaue and we want to divide it into two matrix with 5 number each
#we will get 2*5 matrixes
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
#reshape if we do not know the number of items when dealing with big data but we want to have 2 matrixes using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
#also we can devide torch into unknown number of matrixes but each have 5 number
my_torch2 = my_torch2.reshape(-1,2)
my_torch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [15]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#view
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
#chaning an item in tensor
my_torch3[1] = 100
my_torch3

tensor([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9])

In [20]:
#slice : grabbing a section of the tensor or specific item
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# the index numbers start from zero
#here we want to grab the seventh item not seven
my_torch5[7]

tensor(7)

In [23]:
my_torch6 = my_torch5.reshape(5,2)
my_torch6

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [25]:
#we want to select the second column
#columns start at zero
my_torch6[:,1]

tensor([1, 3, 5, 7, 9])

In [26]:
#but it is look like a row so we want to turn it to column shape
my_torch6 [:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [ ]:
data =[[1,2], [3,4]]

In [ ]:
torch.tensor(data)

tensor([[1, 2],
        [3, 4]])

In [ ]:
zeroes_tensor = torch.zeros (3,4)
zeroes_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones_tensor =  torch.ones (3,4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
eye_tensor = torch.eye (3)
eye_tensor

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
#creating a random tensor
rand_tensor = torch.rand (3,4)
rand_tensor

tensor([[0.6719, 0.8951, 0.0984, 0.5540],
        [0.2088, 0.8054, 0.2321, 0.6996],
        [0.8204, 0.3129, 0.9200, 0.3260]])

In [ ]:
#creating a random tensor with normal values
randn_tensor = torch.randn (3,4)
randn_tensor

tensor([[-0.4619,  1.1118,  0.0324, -1.3546],
        [-0.3334,  0.8055, -0.8321, -1.6651],
        [-2.1412,  0.2219, -2.0417, -0.2494]])

In [ ]:
#creating a random tensor with intiger values  and it needed the minimum and maximum limitation
randint_tensor = torch.randint (1,10 , (3,4))
randint_tensor

tensor([[4, 1, 6, 8],
        [2, 2, 4, 4],
        [4, 5, 6, 2]])

when we have a basic tensor and we want to bult other tensors based on the other tensor dimentions

In [ ]:
base= [[1,2,3],
       [4,5,6],
       [7,8,9]]

In [ ]:
base_tensor = torch.tensor (base, dtype=torch.float32)
base_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

based on the base torch we defined random tensor with the same size with the command of "like"

In [ ]:
randlike_tensor = torch.rand_like(base_tensor) # we give base_tensor as the input
randlike_tensor

tensor([[0.5494, 0.2602, 0.7352],
        [0.7898, 0.1579, 0.3268],
        [0.4641, 0.1369, 0.0677]])

In [ ]:
randint_like_tensor = torch.randint_like (base_tensor, 1,10)
randint_like_tensor

tensor([[2., 3., 2.],
        [8., 1., 1.],
        [1., 9., 5.]])

In [ ]:
zeroslike_tensor = torch.zeros_like (base_tensor)
zeroslike_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
oneslike_tensor = torch.ones_like (base_tensor)
oneslike_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#creating an empty tensor
empty_torch = torch.empty(4,4)
empty_torch

tensor([[ 0.0000e+00,  0.0000e+00, -2.2702e+30,  3.1695e-41],
        [-1.2775e+29,  3.1695e-41,  2.5141e-21,  4.5088e-41],
        [ 1.4013e-45,  0.0000e+00,  1.2612e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [ ]:
#diag will give us a diagonal tensor which its diagonal is the values that we defined
a = torch.rand(3)
a

tensor([0.9429, 0.3695, 0.8797])

In [ ]:
diag_tensor = torch.diag(a)
diag_tensor

tensor([[0.9429, 0.0000, 0.0000],
        [0.0000, 0.3695, 0.0000],
        [0.0000, 0.0000, 0.8797]])

In [ ]:
#torch.arange
#torch.linspace

unsqueeze

In [ ]:
 x = torch.tensor([1, 2, 3, 4])


In [ ]:
torch.unsqueeze(x, 0)


tensor([[1, 2, 3, 4]])

In [ ]:
torch.unsqueeze(x, 1)


tensor([[1],
        [2],
        [3],
        [4]])

squeeze

In [ ]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()


torch.Size([2, 1, 2, 1, 2])

In [ ]:
 y = torch.squeeze(x)
 y.size()


torch.Size([2, 2, 2])

In [ ]:
y = torch.squeeze(x, 0)
y.size()


torch.Size([2, 1, 2, 1, 2])

In [ ]:
y = torch.squeeze(x, 1)
y.size()


torch.Size([2, 2, 1, 2])

In [ ]:
y = torch.squeeze(x, (1, 2, 3))
